/drive_assist_feature:
  ros__parameters:
    attention.activity_timeout_sec: 0.20000000000000001
    attention.lidar_activity_timeout_sec: 0.12
    attention.lidar_below_ground_threshold: 0.10000000000000001
    attention.lidar_ground_clearance_min: 0.10000000000000001
    attention.lidar_half_life: 0.10000000000000001
    attention.lidar_range_min_cutoff: 0
    attention.max_global_point_age_seconds: 2
    attention.pointcloud_activity_timeout_sec: 0.20000000000000001
    attention.pointcloud_confidence_threshold: 0
    attention.status_check_period_sec: 0.050000000000000003
    attention.tof_half_life: 0.10000000000000001
    attention.ultrasonic_activity_timeout_sec: 0.34999999999999998
    attention.ultrasound_ground_clearance_min: 0.10000000000000001
    attention.ultrasound_half_life: 0.10000000000000001
    attention.ultrasound_range_min_cutoff: 0
    attention.use_clearance_polygon: true
    attention.use_pcl_confidence: false
    attention.use_range_confidence: false
    attention.weight_lidar: 0.5
    attention.weight_tof: 0.5
    attention.weight_ultrasonic: 0.050000000000000003
    base_limits.base_max_linear_forward_velocity: 0.84999999999999998
    base_limits.base_max_linear_reverse_velocity: 0.40000000000000002
    base_limits.base_max_turn_rate_left: 1.3999999999999999
    base_limits.base_max_turn_rate_right: 1.3999999999999999
    base_limits.learn_normal_deceleration: true
    base_limits.learn_velocity_scale: false
    base_limits.normal_deceleration_rate: 0.34999999999999998
    brake_assist.corridor_width: 0.5
    brake_assist.demand_angular_projection_scale: 1
    brake_assist.demand_forward_projection_scale: 3.5
    brake_assist.demand_reverse_projection_scale: 3.5
    brake_assist.linear_demand_filter_epsilon: 0.10000000000000001
    drive_assist.clearance_padding: 0
    drive_assist.footprint_extend_forward: 0.14999999999999999
    drive_assist.footprint_extend_reverse: 0.050000000000000003
    drive_assist.footprint_padding: 0.050000000000000003
    feature.error_history:
      []
    minimap.minimap_confidence_threshold: 0
    minimap.minimap_enabled: true
    minimap.minimap_encoding: 2
    minimap.minimap_height: 32
    minimap.minimap_max_publish_rate: 5
    minimap.minimap_resolution: 0.20000000000000001
    minimap.minimap_width: 32
    perception.above_ground_max_z: 0.69999999999999996
    perception.above_ground_min_z: 0.050000000000000003
    perception.confidence_postfilter_threshold: 0
    perception.confidence_prefilter_threshold: 0
    perception.expected_floor_z: 0
    perception.floor_z_range: 0.050000000000000003
    perception.focus_radius: 1
    perception.max_cloud_height: 1.5
    perception.max_obstacle_height: 0.10000000000000001
    perception.max_ramp_angle: 15
    perception.merge_voxel_size: 0.050000000000000003
    perception.normal_z_min: 0.94999999999999996
    perception.overhang_max_z: 1.5
    perception.overhang_min_z: 0.75
    perception.ramp_min_angle: 5
    perception.ramp_plane_distance_threshold: 0.050000000000000003
    perception.temporal_filter: false
    perception.under_ground_max_z: -0.050000000000000003
    potential_field.inflate_in_brake_assist_mode: false
    potential_field.inflate_in_sound_assist_mode: false
    potential_field.inflate_in_steer_assist_mode: false
    potential_field.inflation_radius_min_meters: 0.5
    potential_field.inflation_radius_vel_scaler: 1
    potential_field.inflation_seed_potential_threshold: 0.98999999999999999
    potential_field.inflation_well_enabled: false
    potential_field.inflation_well_inner_distance_meters: 0.5
    potential_field.inflation_well_max_gain: 0.20000000000000001
    potential_field.inflation_well_outer_distance_meters: 2
    potential_field.inflation_well_shape_exponent: 1.5
    potential_field.max_ultrasonic_weight: 0.050000000000000003
    potential_field.min_ultrasonic_weight: 0
    potential_field.publish_sensor_weights: false
    potential_field.use_odom_for_dynamic_inflation: true
    sound_assist.amplitude_percent: 85
    sound_assist.angular_moving_threshold: 0.050000000000000003
    sound_assist.beep_frequency: 440
    sound_assist.linear_moving_threshold: 0.02
    sound_assist.max_beep_duration_ms: 600
    sound_assist.max_distance: 1.5
    sound_assist.max_pause_duration_ms: 700
    sound_assist.min_beep_duration_ms: 120
    sound_assist.min_distance: 0
    sound_assist.min_pause_duration_ms: 50
    steer_assist.angular_demand_filter_epsilon: 0.10000000000000001
    steer_assist.odom_lookahead_max_blend: 0.5
    steer_assist.steer_assist_strength: 1
    steer_assist.steer_influence_width: 0.40000000000000002
    steer_assist.steer_lookahead_gain: 0.40000000000000002
    steer_assist.steer_max_assist: 0.80000000000000004
    steer_assist.steer_min_lookahead: 0.5
    steer_assist.turn_block_full_distance: 0.050000000000000003
    steer_assist.turn_block_start_distance: 0.25
    steer_assist.use_odom_lookahead_blend: true
    tof_sensor.num_of_rays: 64
    tof_sensor.update_rate: 10
checksum: c28eeb85e236447ffcb1f7725e38f9c8b510a73b89d29517e77bfa70eb8ba99c
